---
server:
    install: '1'
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: lostandfound, ip: 192.168.33.99, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /home/vagrant/lostandfound
    servername: lostandfound.dev
mysql:
    install: '1'
    root_password: '123'
    database: lostandfound
    user: lostandfound
    password: '123'
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql]

